[package]
name="bevy_stardust_client"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]

[dependencies]
bevy_stardust_shared = { path = "../shared" }
bevy = { version = "0.11", default-features=false }