[package]
name="bevy_stardust_udp"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
description="A transport layer for bevy_stardust, using native UDP sockets."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy = { version = "0.12", default-features = false }
bevy_stardust = { version = "0.2.0", path = "../stardust" }
rayon = "1.8.0"
anyhow = "1.0.75"
fastrand = "2.0.1"

[dev-dependencies]
bevy = { version = "0.12", default-features = true }
bevy_egui = "0.23.0"