[package]
name="stardust_auth"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]

[dependencies]
rustls = "0.21.5"
rustls-pemfile = "1.0.3"
mio = { version = "0.8.8", features = ["net", "os-poll"] }
clap = { version = "4.3.15", features = ["derive"] }