[package]
name="bevy_stardust_quic"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
description="A transport layer for bevy_stardust that uses QUIC."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy = { version = "0.12", default-features=false }
bevy_stardust = { version = "0.2", path = "../stardust" }
quinn = { version = "0.10", features = ["native-certs", "tls-rustls", "log"] }
quinn-udp = { version = "0.4", default-features = false }
async-io = "2.3"
rustls = { version = "0.21", features = ["quic"] }
ring = "0.17"
anyhow = "1"