[package]
name="bevy_stardust_quic"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
description="A transport layer for bevy_stardust that uses QUIC."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy = { version = "0.12", default-features=false }
bevy_stardust = { version = "0.2", path = "../stardust" }
bytes = "1"
untrusted = "0.9"
quinn-proto = { version = "0.10" }
rustls = { version = "0.21", features = ["quic"] }
ring = "0.17"
anyhow = "1"

[dev-dependencies]
rcgen = "0.12"
rustls-pemfile = "1"

[[example]]
name = "minimal-server"
path = "examples/minimal/server.rs"

[[example]]
name = "minimal-client"
path = "examples/minimal/client.rs"