[package]
name="bevy_stardust_quic"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
description="A transport layer for bevy_stardust that uses QUIC."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy_app = "0.12"
bevy_ecs = "0.12"
bevy_stardust = { version = "0.2", path = "../stardust" }
quinn-proto = { version = "0.10" }
bytes = "1"
untrusted = "0.9"
rustls = { version = "0.21", features = ["quic", "dangerous_configuration"] }
ring = "0.17"
anyhow = "1"
tracing = "0.1"

[dev-dependencies]
rcgen = "0.12"
rustls-pemfile = "1"
bevy_log = "0.12"

[features]
default = []
dangerous = []

[[example]]
name = "minimal-server"
path = "examples/minimal/server.rs"

[[example]]
name = "minimal-client"
path = "examples/minimal/client.rs"