[package]
name="bevy_stardust_quic"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
license="MIT OR Apache-2.0"
description="A QUIC transport layer plugin for bevy_stardust"
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking", "quic"]

[dependencies.bevy]
version = "0.13"
default-features = false

[dependencies.bevy_stardust]
version = "0.6"
path = "../stardust"

[dependencies.bytes]
version = "1.5.0"

[dependencies.anyhow]
version = "1"

[dependencies.quinn-proto]
version = "0.11.3"

[[example]]
name = "simple-server"
path = "examples/simple/server.rs"

[[example]]
name = "simple-client"
path = "examples/simple/client.rs"