[package]
name="bevy_stardust_shared"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]

[dependencies]
bevy = { version = "0.11", default-features=false }
glam = { version = "0.24" }
rand = "0.8.5"
ring = "0.16.20"