[package]
name="bevy_stardust"
version="0.2.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
documentation="https://github.com/Veritius/bevy_stardust/blob/main/docs/README.md"
description="A batteries-included networking crate for the Bevy game engine."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[features]
default = ["udp"]
udp = ["dep:json"]

[dependencies]
# Mandatory dependencies
bevy = { version = "0.12", default-features=false }
semver = "1.0.18"
once_cell = "1.18.0"
smallvec = "1.11.1"
anyhow = "1.0.75"

# UDP transport layer dependencies
json = { version = "0.12.4", optional = true }