[package]
name="bevy_stardust"
version="0.3.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT OR Apache-2.0"
description="A networking crate for the Bevy game engine."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy = { version = "0.12", default-features=false }
bytes = "1.5.0"
smallvec = "1.11.1"