[package]
name="bevy_stardust"
version="0.2.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
readme="../README.md"
license="MIT"
documentation="https://github.com/Veritius/bevy_stardust/blob/main/docs/README.md"
description="A batteries-included networking crate for the Bevy game engine."
repository="https://github.com/veritius/bevy_stardust/"
keywords=["bevy", "gamedev", "networking"]

[dependencies]
bevy = { version = "0.11", default-features=false }
bitvec = "1.0.1"
semver = "1.0.18"
json = "0.12.4"
glam = { version = "0.24" }
rand = "0.8.5"
once_cell = "1.18.0"